name: Testing
on:
  push:

jobs:
  update-benchmark-addon-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Install dependencies"
        run: "apt-get update && apt-get install jq"
      - name: "Setup SSH deploy key"
        uses: webfactory/ssh-agent@fc49353b67b2b7c1e0e6a600572d01a69f2672dd
        with:
          ssh-private-key: ${{ secrets.BENCHMARK_REPO_DEPLOY_KEY }}
      - name: "Push update addon version"
        run: |
          VERSION=$(cat package.json | jq -r ".version")

          git config --global user.name "Anima CI"
          git clone git@github.com:AnimaApp/storybook-collection.git
          cd storybook-collection

          # TODO: remove this once testing is completed
          git checkout testing-ci

          # TODO: read the actual version
          ./scripts/upgrade_addon_version.sh "$VERSION"
          git add -A
          git commit -m "chore(misc): upgrade storybook addon version from CI"
          git push
